// Sex and the City — all 94 episodes
// chars: primary character arcs in the episode
// moods: cozy | sad | laugh | celebratory | restless
// vibes: glamorous | real_talk | fashion | messy | comedy

const EPISODES = [
  // ── SEASON 1 ───────────────────────────────────────────────────────────────
  { id:"s01e01", s:1, e:1, title:"Sex and the City",
    rating:7.3,
    chars:["carrie","samantha"],
    moods:["laugh","restless"],
    vibes:["glamorous","comedy"],
    desc:"The pilot. Carrie starts her column and meets Mr. Big for the very first time." },

  { id:"s01e02", s:1, e:2, title:"Models and Mortals",
    rating:7.2,
    chars:["samantha","miranda"],
    moods:["laugh","restless"],
    vibes:["comedy","glamorous"],
    desc:"Samantha pursues a man famous for dating models. Miranda and Skipper finally get together." },

  { id:"s01e03", s:1, e:3, title:"Bay of Married Pigs",
    rating:7.3,
    chars:["charlotte","miranda"],
    moods:["laugh","cozy"],
    vibes:["comedy","real_talk"],
    desc:"Carrie navigates a Hamptons weekend with married friends. Charlotte meets 'The Marrying Guy.'" },

  { id:"s01e04", s:1, e:4, title:"Valley of the Twenty-Something Guys",
    rating:7.4,
    chars:["carrie"],
    moods:["laugh","restless"],
    vibes:["glamorous","comedy"],
    desc:"Carrie has a fling with a younger man. She and Big arrange their first official drink." },

  { id:"s01e05", s:1, e:5, title:"The Power of Female Sex",
    rating:7.4,
    chars:["carrie","charlotte"],
    moods:["restless","laugh"],
    vibes:["glamorous","messy"],
    desc:"A French architect leaves Carrie money after their encounter. Charlotte poses for an explicit artist." },

  { id:"s01e06", s:1, e:6, title:"Secret Sex",
    rating:7.5,
    chars:["carrie"],
    moods:["restless","sad"],
    vibes:["messy","real_talk"],
    desc:"Carrie and Big go on an official date — but she suspects he's hiding her from his world." },

  { id:"s01e07", s:1, e:7, title:"The Monogamists",
    rating:7.5,
    chars:["carrie"],
    moods:["sad","restless"],
    vibes:["messy","real_talk"],
    desc:"Carrie discovers Big is still seeing other women while they've been dating." },

  { id:"s01e08", s:1, e:8, title:"Three's a Crowd",
    rating:7.4,
    chars:["carrie","charlotte"],
    moods:["laugh","restless"],
    vibes:["comedy","messy"],
    desc:"Charlotte navigates unwanted threesome requests. Carrie feels threatened by Big's ex-wife." },

  { id:"s01e09", s:1, e:9, title:"The Turtle and the Hare",
    rating:7.5,
    chars:["carrie","miranda"],
    moods:["sad","laugh"],
    vibes:["real_talk","comedy"],
    desc:"Big announces he'll never remarry — unsettling Carrie. Miranda introduces the group to her vibrator." },

  { id:"s01e10", s:1, e:10, title:"The Baby Shower",
    rating:7.6,
    chars:["carrie","charlotte","samantha"],
    moods:["sad","cozy"],
    vibes:["real_talk","comedy"],
    desc:"The four escape to a suburban baby shower and have deeply different feelings about it." },

  { id:"s01e11", s:1, e:11, title:"The Drought",
    rating:7.6,
    chars:["carrie","miranda"],
    moods:["sad","laugh"],
    vibes:["real_talk","comedy"],
    desc:"Carrie's sex life with Big dries up. Miranda realizes she hasn't had sex in months." },

  { id:"s01e12", s:1, e:12, title:"Oh Come All Ye Faithful",
    rating:7.7,
    chars:["carrie"],
    moods:["sad","restless"],
    vibes:["messy","real_talk"],
    desc:"Big introduces Carrie to his mother — as 'a friend.' She ends things on the spot." },

  // ── SEASON 2 ───────────────────────────────────────────────────────────────
  { id:"s02e01", s:2, e:1, title:"Take Me Out to the Ballgame",
    rating:7.5,
    chars:["carrie"],
    moods:["laugh","restless"],
    vibes:["glamorous","comedy"],
    desc:"Carrie meets a new Yankee at the ballpark while bracing for her first post-Big encounter." },

  { id:"s02e02", s:2, e:2, title:"The Awful Truth",
    rating:7.6,
    chars:["carrie","miranda"],
    moods:["laugh","sad"],
    vibes:["real_talk","comedy"],
    desc:"Carrie accidentally gets her friend to leave her abusive husband. Miranda tries talking dirty." },

  { id:"s02e03", s:2, e:3, title:"The Freak Show",
    rating:7.6,
    chars:["carrie"],
    moods:["laugh","restless"],
    vibes:["comedy","real_talk"],
    desc:"After a string of strange dates, Carrie wonders if she's the freak. Miranda dates a man who refuses to leave Manhattan." },

  { id:"s02e04", s:2, e:4, title:"They Shoot Single People, Don't They?",
    rating:7.5,
    chars:["carrie","miranda"],
    moods:["laugh","sad"],
    vibes:["real_talk","comedy"],
    desc:"Carrie's NY Magazine photo shoot goes badly wrong. Miranda fakes it with her boyfriend." },

  { id:"s02e05", s:2, e:5, title:"Four Women and a Funeral",
    rating:7.6,
    chars:["carrie","miranda"],
    moods:["restless","cozy"],
    vibes:["real_talk","glamorous"],
    desc:"Carrie starts seeing Big again. Miranda buys her own apartment on the Upper West Side." },

  { id:"s02e06", s:2, e:6, title:"The Cheating Curve",
    rating:7.5,
    chars:["carrie","charlotte"],
    moods:["laugh","restless"],
    vibes:["glamorous","comedy"],
    desc:"Carrie officially dates Big again. Charlotte falls in with a fabulous new group — the Power Lesbians." },

  { id:"s02e07", s:2, e:7, title:"The Chicken Dance",
    rating:7.6,
    chars:["carrie","miranda"],
    moods:["laugh","sad"],
    vibes:["comedy","messy"],
    desc:"Carrie gets fed up with Big ignoring her. Miranda accidentally ruins a long-distance romance." },

  { id:"s02e08", s:2, e:8, title:"The Man, the Myth, the Viagra",
    rating:7.6,
    chars:["carrie","miranda"],
    moods:["laugh","restless"],
    vibes:["comedy","real_talk"],
    desc:"Carrie tries to get Big to meet the girls. Miranda meets Steve Brady — a cute bartender who wants commitment." },

  { id:"s02e09", s:2, e:9, title:"Old Dogs, New Dicks",
    rating:7.5,
    chars:["carrie","miranda"],
    moods:["laugh","restless"],
    vibes:["comedy","real_talk"],
    desc:"Carrie tries to change Big's wandering eye. Miranda and Steve clash over their opposite schedules." },

  { id:"s02e10", s:2, e:10, title:"The Caste System",
    rating:7.5,
    chars:["carrie","miranda"],
    moods:["restless","sad"],
    vibes:["glamorous","real_talk"],
    desc:"Carrie gets a peek into Big's real world at an Upper East Side dinner. Miranda and Steve argue about money." },

  { id:"s02e11", s:2, e:11, title:"Evolution",
    rating:7.7,
    chars:["carrie","miranda"],
    moods:["sad","restless"],
    vibes:["real_talk","messy"],
    desc:"Carrie attempts to leave her things at Big's place. Miranda learns one of her ovaries has stopped working." },

  { id:"s02e12", s:2, e:12, title:"La Douleur Exquise!",
    rating:7.7,
    chars:["carrie","charlotte"],
    moods:["sad","restless"],
    vibes:["messy","real_talk"],
    desc:"Big casually mentions he's moving to Paris for seven months. Charlotte takes tantric sex classes." },

  { id:"s02e13", s:2, e:13, title:"Games People Play",
    rating:7.6,
    chars:["carrie"],
    moods:["laugh","restless"],
    vibes:["comedy","glamorous"],
    desc:"Carrie starts therapy about Big. She dates a fellow patient — played by Jon Bon Jovi." },

  { id:"s02e14", s:2, e:14, title:"The Fuck Buddy",
    rating:7.6,
    chars:["carrie","miranda"],
    moods:["laugh","restless"],
    vibes:["comedy","real_talk"],
    desc:"Carrie tries to upgrade a casual arrangement into a real relationship." },

  { id:"s02e15", s:2, e:15, title:"Shortcomings",
    rating:7.5,
    chars:["carrie","miranda"],
    moods:["laugh"],
    vibes:["comedy","real_talk"],
    desc:"Carrie dates an author with a very specific problem. Miranda dates a divorced dad." },

  { id:"s02e16", s:2, e:16, title:"Was It Good for You?",
    rating:7.5,
    chars:["carrie"],
    moods:["laugh","restless"],
    vibes:["comedy","real_talk"],
    desc:"Carrie attracts a recovering alcoholic who becomes obsessed with her." },

  { id:"s02e17", s:2, e:17, title:"Twenty-Something Girls vs. Thirty-Something Women",
    rating:7.9,
    chars:["carrie"],
    moods:["sad","restless"],
    vibes:["glamorous","messy"],
    desc:"Carrie runs into Big at the Hamptons — with his gorgeous 27-year-old girlfriend Natasha." },

  { id:"s02e18", s:2, e:18, title:"Ex and the City",
    rating:8.1,
    chars:["carrie","miranda"],
    moods:["sad","restless"],
    vibes:["messy","real_talk"],
    desc:"Big is engaged. Carrie has to process what that means. Miranda ends up back in bed with Steve." },

  // ── SEASON 3 ───────────────────────────────────────────────────────────────
  { id:"s03e01", s:3, e:1, title:"Where There's Smoke...",
    rating:7.7,
    chars:["carrie","miranda"],
    moods:["laugh","restless"],
    vibes:["comedy","glamorous"],
    desc:"Carrie meets a hot politician at a Staten Island FDNY calendar benefit." },

  { id:"s03e02", s:3, e:2, title:"Politically Erect",
    rating:7.7,
    chars:["carrie","miranda"],
    moods:["laugh","restless"],
    vibes:["comedy","real_talk"],
    desc:"The politician has a golden shower fetish. Miranda asks Steve to go steady." },

  { id:"s03e03", s:3, e:3, title:"Attack of the 5'10\" Woman",
    rating:7.8,
    chars:["carrie","miranda"],
    moods:["sad","restless"],
    vibes:["messy","real_talk"],
    desc:"Carrie runs face-to-face into Natasha — Big's wife. Miranda hires Magda the opinionated maid." },

  { id:"s03e04", s:3, e:4, title:"Boy, Girl, Boy, Girl...",
    rating:7.6,
    chars:["carrie"],
    moods:["laugh","restless"],
    vibes:["comedy","real_talk"],
    desc:"Carrie dates a bisexual twenty-something and gets challenged on her own open-mindedness." },

  { id:"s03e05", s:3, e:5, title:"No Ifs, Ands, or Butts",
    rating:7.8,
    chars:["carrie","miranda"],
    moods:["laugh","cozy"],
    vibes:["real_talk","comedy"],
    desc:"Carrie starts dating Aidan Shaw — and her smoking habit becomes a problem." },

  { id:"s03e06", s:3, e:6, title:"Are We Sluts?",
    rating:7.7,
    chars:["carrie","miranda"],
    moods:["laugh","restless"],
    vibes:["comedy","real_talk"],
    desc:"Aidan makes Carrie wait. Miranda discovers she has chlamydia and has to call every ex." },

  { id:"s03e07", s:3, e:7, title:"Drama Queens",
    rating:7.7,
    chars:["carrie"],
    moods:["cozy","restless"],
    vibes:["real_talk","messy"],
    desc:"Carrie is in a perfect relationship with Aidan — and is somehow more anxious than ever." },

  { id:"s03e08", s:3, e:8, title:"The Big Time",
    rating:7.8,
    chars:["carrie","charlotte"],
    moods:["restless","sad"],
    vibes:["messy","real_talk"],
    desc:"Big confesses he misses Carrie. Charlotte falls madly in love with Trey after just weeks." },

  { id:"s03e09", s:3, e:9, title:"Easy Come, Easy Go",
    rating:7.7,
    chars:["carrie","charlotte","miranda"],
    moods:["restless","sad"],
    vibes:["messy","real_talk"],
    desc:"Big says he's leaving his wife. Miranda breaks up with Steve. Charlotte maneuvers Trey into a proposal." },

  { id:"s03e10", s:3, e:10, title:"All or Nothing",
    rating:7.8,
    chars:["carrie","charlotte"],
    moods:["sad","restless"],
    vibes:["messy","real_talk"],
    desc:"Carrie feels guilty and tries to end the affair with Big. Charlotte negotiates her prenup." },

  { id:"s03e11", s:3, e:11, title:"Running with Scissors",
    rating:7.9,
    chars:["carrie"],
    moods:["restless","sad"],
    vibes:["messy","real_talk"],
    desc:"The affair becomes public — Natasha catches them and falls down the stairs chasing Carrie." },

  { id:"s03e12", s:3, e:12, title:"Don't Ask, Don't Tell",
    rating:8.0,
    chars:["carrie","charlotte"],
    moods:["sad","restless"],
    vibes:["messy","real_talk"],
    desc:"Carrie has to confess the affair to Aidan. Charlotte marries Trey despite discovering his impotence." },

  { id:"s03e13", s:3, e:13, title:"Escape from New York",
    rating:7.7,
    chars:["carrie"],
    moods:["laugh","restless"],
    vibes:["glamorous","comedy"],
    desc:"The girls head to LA. Carrie meets Matthew McConaughey about optioning her column." },

  { id:"s03e14", s:3, e:14, title:"Sex and Another City",
    rating:7.7,
    chars:["carrie","samantha"],
    moods:["laugh","celebratory"],
    vibes:["glamorous","comedy"],
    desc:"LA girls' trip: celebrity perks, Hugh Hefner, and a night at the Playboy Mansion." },

  { id:"s03e15", s:3, e:15, title:"Hot Child in the City",
    rating:7.9,
    chars:["samantha","charlotte"],
    moods:["laugh"],
    vibes:["comedy","real_talk"],
    desc:"Samantha plans a bar mitzvah for a spoiled teen. Charlotte catches Trey masturbating." },

  { id:"s03e16", s:3, e:16, title:"Frenemies",
    rating:7.6,
    chars:["carrie","miranda"],
    moods:["laugh","restless"],
    vibes:["comedy","real_talk"],
    desc:"Carrie teaches a class on finding love. Miranda dates one of Carrie's exes, met at a funeral." },

  { id:"s03e17", s:3, e:17, title:"What Goes Around Comes Around",
    rating:7.8,
    chars:["carrie","charlotte"],
    moods:["sad","restless"],
    vibes:["messy","real_talk"],
    desc:"Carrie decides she needs to clear her karma and face Natasha. Charlotte and Trey decide to separate." },

  { id:"s03e18", s:3, e:18, title:"Cock a Doodle Do!",
    rating:8.0,
    chars:["carrie","charlotte"],
    moods:["celebratory","cozy"],
    vibes:["real_talk","glamorous"],
    desc:"Carrie meets with Big for the first time since his marriage ended. Season 3 ends on a hopeful note." },

  // ── SEASON 4 ───────────────────────────────────────────────────────────────
  { id:"s04e01", s:4, e:1, title:"The Agony and the 'Ex'-tacy",
    rating:7.7,
    chars:["carrie","samantha"],
    moods:["sad","laugh"],
    vibes:["real_talk","comedy"],
    desc:"No one shows up for Carrie's birthday. The four make a pact: they are each other's significant others." },

  { id:"s04e02", s:4, e:2, title:"The Real Me",
    rating:8.2,
    chars:["carrie","charlotte","samantha"],
    moods:["celebratory","laugh"],
    vibes:["fashion","glamorous"],
    desc:"Carrie walks in a fashion show. The iconic episode where all four wrestle with their own beauty." },

  { id:"s04e03", s:4, e:3, title:"Defining Moments",
    rating:7.6,
    chars:["carrie","samantha"],
    moods:["restless","laugh"],
    vibes:["glamorous","real_talk"],
    desc:"Carrie meets a jazz musician. Samantha questions her sexuality after falling for a female artist." },

  { id:"s04e04", s:4, e:4, title:"What's Sex Got to Do with It?",
    rating:7.6,
    chars:["carrie","samantha"],
    moods:["laugh","restless"],
    vibes:["comedy","real_talk"],
    desc:"Carrie dates the jazzman but he has ADHD and can't focus. Samantha announces she's in a lesbian relationship." },

  { id:"s04e05", s:4, e:5, title:"Ghost Town",
    rating:7.7,
    chars:["carrie","miranda","charlotte"],
    moods:["restless","laugh"],
    vibes:["real_talk","comedy"],
    desc:"Carrie is invited to the opening of Steve and Aidan's bar. Miranda thinks her apartment is haunted." },

  { id:"s04e06", s:4, e:6, title:"Baby, Talk Is Cheap",
    rating:7.6,
    chars:["carrie","charlotte"],
    moods:["restless","cozy"],
    vibes:["real_talk","messy"],
    desc:"Carrie realizes she wants Aidan back. Charlotte and Trey start trying for a baby." },

  { id:"s04e07", s:4, e:7, title:"Time and Punishment",
    rating:7.7,
    chars:["carrie","charlotte"],
    moods:["restless","sad"],
    vibes:["messy","real_talk"],
    desc:"Big calls Carrie while she's in bed with Aidan. Charlotte quits her job to focus on getting pregnant." },

  { id:"s04e08", s:4, e:8, title:"My Motherboard, My Self",
    rating:8.0,
    chars:["carrie","miranda","charlotte","samantha"],
    moods:["sad"],
    vibes:["real_talk","messy"],
    desc:"Miranda's mother dies. The entire episode is about grief, what we have, and what we lose." },

  { id:"s04e09", s:4, e:9, title:"Sex and the Country",
    rating:7.5,
    chars:["carrie","miranda"],
    moods:["cozy","sad"],
    vibes:["real_talk","messy"],
    desc:"Carrie at Aidan's country house, feeling like a fish out of water. Miranda faces Steve's health crisis." },

  { id:"s04e10", s:4, e:10, title:"Belles of the Balls",
    rating:7.6,
    chars:["carrie","miranda"],
    moods:["restless","cozy"],
    vibes:["real_talk","messy"],
    desc:"Carrie invites Big to Aidan's country house — terrible idea. Miranda nurses Steve back to health." },

  { id:"s04e11", s:4, e:11, title:"Coulda, Woulda, Shoulda",
    rating:7.8,
    chars:["carrie","miranda","charlotte"],
    moods:["sad","restless"],
    vibes:["real_talk","messy"],
    desc:"Carrie tells Aidan about her past abortion. Miranda discovers she's pregnant and debates what to do." },

  { id:"s04e12", s:4, e:12, title:"Just Say Yes",
    rating:7.9,
    chars:["carrie","miranda","charlotte"],
    moods:["celebratory","restless"],
    vibes:["messy","real_talk"],
    desc:"Aidan proposes. Miranda tells Steve she's pregnant. Big decisions all around." },

  { id:"s04e13", s:4, e:13, title:"The Good Fight",
    rating:7.7,
    chars:["carrie","miranda","charlotte"],
    moods:["restless","laugh"],
    vibes:["messy","comedy"],
    desc:"Aidan moves in and Carrie's apartment turns into a war zone of clutter and incompatible habits." },

  { id:"s04e14", s:4, e:14, title:"All That Glitters",
    rating:7.7,
    chars:["carrie","samantha","charlotte"],
    moods:["laugh","celebratory"],
    vibes:["glamorous","comedy"],
    desc:"Carrie finds a gay best friend and parties at Bungalow 8. Charlotte and Trey finally end things." },

  { id:"s04e15", s:4, e:15, title:"Change of a Dress",
    rating:7.8,
    chars:["carrie","miranda","samantha"],
    moods:["restless","sad"],
    vibes:["messy","real_talk"],
    desc:"Carrie panics at the idea of marrying Aidan. Miranda learns her baby's gender. Samantha catches Richard cheating." },

  { id:"s04e16", s:4, e:16, title:"Ring a Ding Ding",
    rating:7.8,
    chars:["carrie"],
    moods:["restless","sad"],
    vibes:["messy","real_talk"],
    desc:"Carrie has to buy back her apartment from Aidan — or lose it. She faces the financial cost of her romantic choices." },

  { id:"s04e17", s:4, e:17, title:"A 'Vogue' Idea",
    rating:7.8,
    chars:["carrie","samantha"],
    moods:["celebratory","laugh"],
    vibes:["fashion","glamorous"],
    desc:"Carrie starts working at Vogue. Her acerbic editor (Candice Bergen) tells her she has no Vogue ideas." },

  { id:"s04e18", s:4, e:18, title:"I Heart NY",
    rating:8.1,
    chars:["carrie","miranda"],
    moods:["sad","celebratory"],
    vibes:["real_talk","messy"],
    desc:"Big is moving to Napa. Carrie gives him a proper NYC send-off. Miranda gives birth to Brady." },

  // ── SEASON 5 ───────────────────────────────────────────────────────────────
  { id:"s05e01", s:5, e:1, title:"Anchors Away",
    rating:7.6,
    chars:["carrie","miranda"],
    moods:["sad","laugh"],
    vibes:["real_talk","comedy"],
    desc:"Fleet Week arrives. Carrie realizes her relationship with New York is just as complicated as her love life." },

  { id:"s05e02", s:5, e:2, title:"Unoriginal Sin",
    rating:7.5,
    chars:["carrie","miranda"],
    moods:["celebratory","cozy"],
    vibes:["real_talk","glamorous"],
    desc:"A publisher wants Carrie's column as a book. Miranda asks Carrie to be Brady's godmother." },

  { id:"s05e03", s:5, e:3, title:"Luck Be an Old Lady",
    rating:7.5,
    chars:["carrie","charlotte","miranda","samantha"],
    moods:["laugh","celebratory"],
    vibes:["comedy","glamorous"],
    desc:"Charlotte's birthday trip to Atlantic City. The four are at their chaotic, loving best." },

  { id:"s05e04", s:5, e:4, title:"Cover Girl",
    rating:7.6,
    chars:["carrie","samantha"],
    moods:["laugh","sad"],
    vibes:["fashion","real_talk"],
    desc:"Carrie agonizes over her book cover look. Miranda joins Weight Watchers. Samantha feels judged for her past." },

  { id:"s05e05", s:5, e:5, title:"Plus One Is the Loneliest Number",
    rating:7.6,
    chars:["carrie","samantha"],
    moods:["laugh","sad"],
    vibes:["glamorous","comedy"],
    desc:"Carrie meets Berger at her book launch. Samantha's chemical peel goes catastrophically wrong." },

  { id:"s05e06", s:5, e:6, title:"Critical Condition",
    rating:7.6,
    chars:["carrie","miranda"],
    moods:["sad","laugh"],
    vibes:["real_talk","comedy"],
    desc:"Carrie runs into Aidan's new girlfriend. Miranda is drowning in new-mom logistics." },

  { id:"s05e07", s:5, e:7, title:"The Big Journey",
    rating:7.7,
    chars:["carrie","samantha","charlotte"],
    moods:["cozy","laugh"],
    vibes:["glamorous","real_talk"],
    desc:"Carrie travels to San Francisco for her book tour and tracks Big down. Charlotte starts something with Harry." },

  { id:"s05e08", s:5, e:8, title:"I Love a Charade",
    rating:7.8,
    chars:["carrie","charlotte","samantha"],
    moods:["celebratory","laugh"],
    vibes:["glamorous","comedy"],
    desc:"The group attends a wild Hamptons wedding. Carrie and Berger reconnect. Charlotte declares her love for Harry." },

  // ── SEASON 6 ───────────────────────────────────────────────────────────────
  { id:"s06e01", s:6, e:1, title:"To Market, to Market",
    rating:7.7,
    chars:["carrie","miranda","charlotte"],
    moods:["restless","laugh"],
    vibes:["comedy","real_talk"],
    desc:"Carrie's first date with Berger. Miranda realizes her feelings for Steve — right as he starts dating someone new." },

  { id:"s06e02", s:6, e:2, title:"Great Sexpectations",
    rating:7.6,
    chars:["carrie","samantha"],
    moods:["laugh","restless"],
    vibes:["comedy","real_talk"],
    desc:"Carrie and Berger finally sleep together and it's... a disappointment. Samantha meets Smith Jerrod." },

  { id:"s06e03", s:6, e:3, title:"The Perfect Present",
    rating:7.6,
    chars:["miranda","charlotte"],
    moods:["restless","laugh"],
    vibes:["comedy","real_talk"],
    desc:"Miranda finds condoms in Brady's diaper bag — Steve is seeing someone. Charlotte adjusts to life without Christmas." },

  { id:"s06e04", s:6, e:4, title:"Pick-A-Little, Talk-A-Little",
    rating:7.7,
    chars:["carrie","miranda","samantha"],
    moods:["laugh","restless"],
    vibes:["comedy","real_talk"],
    desc:"Berger teaches Miranda how to decode a man's signals. Charlotte hosts her first Shabbat dinner." },

  { id:"s06e05", s:6, e:5, title:"Lights, Camera, Relationship!",
    rating:7.7,
    chars:["carrie","samantha"],
    moods:["restless","sad"],
    vibes:["messy","real_talk"],
    desc:"Carrie's book royalties arrive — and Berger's book deal falls through the same day." },

  { id:"s06e06", s:6, e:6, title:"Hop, Skip, and a Week",
    rating:7.6,
    chars:["carrie","charlotte","samantha"],
    moods:["sad","restless"],
    vibes:["messy","real_talk"],
    desc:"Berger asks for a break. Charlotte reconnects with Harry at a singles event. Samantha renames Jerry 'Smith.'" },

  { id:"s06e07", s:6, e:7, title:"The Post-It Always Sticks Twice",
    rating:7.9,
    chars:["carrie"],
    moods:["restless","laugh"],
    vibes:["messy","comedy"],
    desc:"Berger breaks up with Carrie via Post-It note. Iconic. The girls rally." },

  { id:"s06e08", s:6, e:8, title:"The Catch",
    rating:7.6,
    chars:["carrie","miranda","charlotte"],
    moods:["restless","sad"],
    vibes:["messy","real_talk"],
    desc:"Carrie tries trapeze classes to confront why she can't commit. Miranda fears Steve's new girlfriend." },

  { id:"s06e09", s:6, e:9, title:"A Woman's Right to Shoes",
    rating:8.0,
    chars:["carrie","miranda"],
    moods:["laugh","restless"],
    vibes:["real_talk","comedy"],
    desc:"Carrie's Manolos are stolen at a friend's party — and the hostess refuses to pay. A fan-favorite on single vs. married." },

  { id:"s06e10", s:6, e:10, title:"Boy, Interrupted",
    rating:7.7,
    chars:["carrie","miranda"],
    moods:["laugh","cozy"],
    vibes:["comedy","real_talk"],
    desc:"Carrie's high school sweetheart reappears. Miranda falls for her hot doctor neighbor." },

  { id:"s06e11", s:6, e:11, title:"The Domino Effect",
    rating:7.8,
    chars:["carrie","miranda","samantha"],
    moods:["sad","restless"],
    vibes:["messy","real_talk"],
    desc:"Big needs heart surgery and Carrie spirals. Miranda grows close to Robert but can't stop thinking about Steve." },

  { id:"s06e12", s:6, e:12, title:"One",
    rating:7.9,
    chars:["carrie","miranda","charlotte"],
    moods:["sad","restless"],
    vibes:["messy","real_talk"],
    desc:"Carrie meets Aleksandr Petrovsky. Miranda can't say 'I love you' to Robert. Charlotte loses a pregnancy." },

  { id:"s06e13", s:6, e:13, title:"Let There Be Light",
    rating:7.8,
    chars:["carrie","miranda","charlotte"],
    moods:["cozy","sad"],
    vibes:["real_talk","messy"],
    desc:"Steve moves back in with Miranda. Charlotte processes her miscarriage. Carrie falls deeper into Petrovsky." },

  { id:"s06e14", s:6, e:14, title:"The Ick Factor",
    rating:7.7,
    chars:["miranda","samantha"],
    moods:["celebratory","sad"],
    vibes:["real_talk","comedy"],
    desc:"Miranda's City Hall wedding. Samantha gets a diagnosis that changes the season." },

  { id:"s06e15", s:6, e:15, title:"Catch-38",
    rating:7.8,
    chars:["carrie","miranda","samantha"],
    moods:["sad","restless"],
    vibes:["messy","real_talk"],
    desc:"Aleksandr doesn't want more children. Samantha starts chemo. Miranda and Steve honeymoon." },

  { id:"s06e16", s:6, e:16, title:"Out of the Frying Pan",
    rating:7.9,
    chars:["carrie","samantha","charlotte"],
    moods:["sad"],
    vibes:["real_talk","messy"],
    desc:"Samantha loses her hair. Carrie is furious Aleksandr barely flinches. Charlotte adopts a dog named Elizabeth Taylor." },

  { id:"s06e17", s:6, e:17, title:"The Cold War",
    rating:7.7,
    chars:["carrie","miranda","samantha"],
    moods:["sad","restless"],
    vibes:["messy","real_talk"],
    desc:"Aleksandr keeps Carrie out of his world. Samantha shoots an intimate film with Smith to fight tabloid rumors." },

  { id:"s06e18", s:6, e:18, title:"Splat!",
    rating:8.0,
    chars:["carrie"],
    moods:["restless","sad"],
    vibes:["messy","glamorous"],
    desc:"A beloved character dies at a party. It pushes Carrie toward the biggest decision of her life." },

  { id:"s06e19", s:6, e:19, title:"An American Girl in Paris (Part Une)",
    rating:8.3,
    chars:["carrie"],
    moods:["sad","cozy"],
    vibes:["glamorous","messy"],
    desc:"Carrie's last dinner in New York with her girls. Paris isn't what she expected. Big gets on a plane." },

  { id:"s06e20", s:6, e:20, title:"An American Girl in Paris (Part Deux)",
    rating:8.7,
    chars:["carrie","samantha","charlotte","miranda"],
    moods:["cozy","celebratory","sad"],
    vibes:["glamorous","real_talk","messy"],
    desc:"The series finale. Everything resolves — Samantha, Miranda, Charlotte, and finally, Carrie and Big." },
];
